CREATE SCHEMA IF NOT EXISTS chat;

CREATE TABLE IF NOT EXISTS chat.users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS chat.token (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token_name VARCHAR(250) NOT NULL
);